# dockerfile for rchats use a bind volume for the config

FROM rust AS builder

WORKDIR /app

COPY . .

# Install dependencies
RUN apt-get update && apt-get install -y pkg-config libssl-dev build-essential

WORKDIR /app/server

RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/release/server /app/server
RUN mkdir -p /app/files/chat_data
RUN mkdir -p /app/files/server_data/config

CMD ["./server"]