#example config for the entire service of rchats with psql and the chat server edit as needed

services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepasswd123
      POSTGRES_DB: rchats
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d

  rchats:
    image: rchats
    container_name: rchats
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/data/ # need to create te config dir on local folder
      - chat_data:/app/data/chat_data

volumes:
  pgdata: {} 
  chat_data: 